In [25]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
#import warnings
#warnings.filterwarnings('ignore')

In [6]:
data = pd.DataFrame({
    "Hours_Studied": [2, 3, 5, 6, 1, 7, 8, 4, 9, 10, 5, 3],
    "Attendance": [60, 65, 75, 80, 55, 90, 95, 70, 98, 100, 85, 68],
    "Extra_Class": ["Yes", "No", "Yes", "No", "No", "Yes", "Yes", "No", "Yes", "No", "No", "Yes"],
    "Grade": ["Fail", "Fail", "Pass", "Pass", "Fail", "Pass", "Pass", "Fail", "Pass", "Pass", "Pass", "Fail"]
})

data

Hours_Studied  Attendance Extra_Class Grade
0               2          60         Yes  Fail
1               3          65          No  Fail
2               5          75         Yes  Pass
3               6          80          No  Pass
4               1          55          No  Fail
5               7          90         Yes  Pass
6               8          95         Yes  Pass
7               4          70          No  Fail
8               9          98         Yes  Pass
9              10         100          No  Pass
10              5          85          No  Pass
11              3          68         Yes  Fail

from matplotlib import pyplot as plt
data['Hours_Studied'].plot(kind='hist', bins=20, title='Hours_Studied')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Attendance'].plot(kind='hist', bins=20, title='Attendance')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
data.groupby('Extra_Class').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
data.groupby('Grade').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='Hours_Studied', y='Attendance', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Hours_Studied'].plot(kind='line', figsize=(8, 4), title='Hours_Studied')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
data['Attendance'].plot(kind='line', figsize=(8, 4), title='Attendance')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Grade'].value_counts()
    for x_label, grp in data.groupby('Extra_Class')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Extra_Class')
_ = plt.ylabel('Grade')

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Extra_Class'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Hours_Studied', y='Extra_Class', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Grade'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Hours_Studied', y='Grade', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Extra_Class'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Attendance', y='Extra_Class', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Grade'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Attendance', y='Grade', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [7]:
X=data[["Hours_Studied","Attendance","Extra_Class"]]
y=data["Grade"]

In [8]:
num_features=["Hours_Studied","Attendance"]
cat_features=["Extra_Class"]

In [14]:
num_transformer=Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler",StandardScaler())
    ])

In [16]:
cat_transformer=Pipeline(steps=[
    ("imputer",SimpleImputer(strategy="most_frequent")),
    ("scaler", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

In [17]:
preprocessor=ColumnTransformer([
    ("num",num_transformer,num_features),
    ("cat",cat_transformer,cat_features)
])

In [29]:
#Create model in the pipeline
# Using one model
#model=Pipeline([
#    ("preprocessor",preprocessor),
#    ("classifier",LogisticRegression())
#])

# Using multiple models
models={
    "LogisticRegression":LogisticRegression(),
    "DecisionTreeClassifier":DecisionTreeClassifier(),
    "KNN Classifier":KNeighborsClassifier()
}

In [33]:
X_train, x_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# Apply the preprocessor to the training and testing data
#Using one model
#model.fit(X_train,y_train)
#print (x_test)
#y_pred=model.predict(x_test)
#print(y_pred)

In [41]:
for name,model in models.items():
  clf=Pipeline([
      ("preprocessor", preprocessor),
      ("classifier",model)
  ])
  clf.fit(X_train,y_train)
  y_pred=clf.predict(x_test)
  #y_pred=model.predict(x_test,y_test)
  accuracy=accuracy_score(y_test,y_pred)
  cm = confusion_matrix(y_test,y_pred)
  cr = classification_report(y_test,y_pred)
  print("Model:",name)
  print("Accuracy:",accuracy)
  print("Confusion Matrix:\n",cm)
  print("Classification Report:\n",cr)

Model: LogisticRegression
Accuracy: 1.0
Confusion Matrix:
 [[1 0]
 [0 2]]
Classification Report:
               precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         1
        Pass       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

Model: DecisionTreeClassifier
Accuracy: 1.0
Confusion Matrix:
 [[1 0]
 [0 2]]
Classification Report:
               precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         1
        Pass       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

Model: KNN Classifier
Accuracy: 1.0
Confusion Matrix:
 [[1 0]
 [0 2]]
Classification Report:
               precision    recall  f1-score   suppor

In [23]:
#Evaluation for this model - One model example

accuracy=accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test,y_pred)
cr = classification_report(y_test,y_pred)
print("Accuracy:",accuracy)
print("Confusion Matrix:\n",cm)
print("Classification Report:\n",cr)

Accuracy: 1.0
Confusion Matrix:
 [[1 0]
 [0 2]]
Classification Report:
               precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         1
        Pass       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

