Starting TensorFlow Basics:

In [1]:
import tensorflow as tf

In [2]:
#to check if module is imported properly
print(tf.__version__)

2.19.0


In [7]:
#constant - not changeable
#creating tensor with constant
scalar=tf.constant(9)
scalar
scalar2=tf.constant([10,10])
scalar2

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [9]:
scalar2.ndim #dimension number

1

In [14]:
matrix=tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [11]:
matrix.ndim

2

In [17]:
thirdmatrix=tf.constant(
    [
    [[1,2,3],
    [2,4,5]],

    [[7,9,3],
    [10,4,5]],

    [[1,2,3],
    [2,4,5]],
            ])
thirdmatrix


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  5]],

       [[ 7,  9,  3],
        [10,  4,  5]],

       [[ 1,  2,  3],
        [ 2,  4,  5]]], dtype=int32)>

In [19]:
thirdmatrix.ndim

3

In [22]:
#tensor: an n-dimensional array of numbers
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [25]:
# Find the shape, rank and size of the tensors
print ("Scalar Information")
print ("Shape:", scalar.shape)
print ("Dimension:", scalar.ndim)
print ("Size:",tf.size(scalar))
print ("Rank: ",tf.rank(scalar).numpy())

Scalar Information
Shape: ()
Dimension: 0
Size: tf.Tensor(1, shape=(), dtype=int32)
Rank:  0


In [26]:
# Creating tensor using variable
changeable_tensor = tf.Variable([10, 7]) #created using Variable
unchangeable_tensor = tf.constant([10,7]) #created using constant
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [28]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [29]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [30]:
unchangeable_tensor[0].assign(5)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [32]:
#Random Tensors
random_tensor = tf.random.Generator.from_seed(42)
random_tensor = random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [33]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.07874262, 0.36794472, 0.48915935, ..., 0.5782858 , 0.9844885 ,
        0.38319623],
       [0.5368093 , 0.9955658 , 0.08897769, ..., 0.95115566, 0.73566127,
        0.99599564],
       [0.22644818, 0.9978225 , 0.9289694 , ..., 0.98463345, 0.29514575,
        0.17295015],
       ...,
       [0.5360522 , 0.09279478, 0.01529181, ..., 0.5307455 , 0.8413441 ,
        0.73881733],
       [0.31892478, 0.28516197, 0.16838801, ..., 0.4604417 , 0.76530814,
        0.63409805],
       [0.8209728 , 0.24396777, 0.10652769, ..., 0.12097263, 0.15806985,
        0.50920296]], dtype=float32)>

In [36]:
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
# The normal method should be called on the generator, not the tensor
random_tensor_3_new = tf.random.Generator.from_seed(42).normal(shape=(3,2))
random_tensor_3,random_tensor_4, random_tensor_3_new

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [37]:
#creating tensors using zeros
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [38]:
#creating tensors using zeros
tensor_ones=tf.ones(shape=(3,4),dtype=tf.dtypes.int16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [44]:

import numpy as np
numpy_Array = np.arange(1,25, dtype=np.int16)
numpy_Array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [45]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [48]:
print ("Tensor Information")
print ("Shape:", tensor_numpy.shape)
print ("Dimension:", tensor_numpy.ndim)
print ("Size:",tf.size(tensor_numpy))
print ("Rank: ",tf.rank(tensor_numpy).numpy())
print ("DataType of elements: ",tensor_numpy.dtype)
print ("Element along axis 0: ",tensor_numpy.shape[0])
print ("Element along axis 1: ", tensor_numpy.shape[1])
print ("Element along axis 2: ", tensor_numpy.shape[2])
print ("Total number of element: \t", tf.size(tensor_numpy).numpy())


Tensor Information
Shape: (2, 3, 4)
Dimension: 3
Size: tf.Tensor(24, shape=(), dtype=int32)
Rank:  3
DataType of elements:  <dtype: 'int16'>
Element along axis 0:  2
Element along axis 1:  3
Element along axis 2:  4
Total number of element: 	 24


In [49]:
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [51]:
#first two elements of each dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

** Arithmetic Operation with Tensor **


*   Add
*   Sub
*  Multi
* Div



In [52]:
tensor_1 = tf.constant([[11,9],[2,5]])
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [59]:
#tensor_1+15
tf.add(tensor_1,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [61]:
#tensor_1-5
tf.subtract(tensor_1,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [-3,  0]], dtype=int32)>

In [63]:
#tensor_1/2
tf.divide(tensor_1,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [1. , 2.5]])>

In [62]:
#tensor_1*2
tf.multiply(tensor_1,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [ 4, 10]], dtype=int32)>

In [64]:
second_matrix = tf.constant([[8,16],[64,8.25],
                             [625, 9.23],
                             [125,2.34],
                             [169,144]], dtype=tf.float32)
print (second_matrix)

tf.Tensor(
[[  8.    16.  ]
 [ 64.     8.25]
 [625.     9.23]
 [125.     2.34]
 [169.   144.  ]], shape=(5, 2), dtype=float32)


In [65]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.828427 ,  4.       ],
       [ 8.       ,  2.8722813],
       [25.       ,  3.0380914],
       [11.18034  ,  1.5297059],
       [13.       , 12.       ]], dtype=float32)>

**Exercise**
Create two tensors with random values between 0 and 1, shape is [6,300]
Find out the following details:
* Number of elements
* Size
* Rank
* Shape

In [70]:
tensor_a = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)
#random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
print ("Tensor Information")
print ("Shape:", tensor_a.shape)
print ("Dimension:", tensor_a.ndim)
print ("Size:",tf.size(tensor_a))
print ("Rank: ",tf.rank(tensor_a).numpy())
print ("DataType of elements: ",tensor_a.dtype)
#print ("Element along axis 0: ",tensor_a.shape[0])
#print ("Element along axis 1: ", tensor_a.shape[1])
#print ("Element along axis 2: ", tensor_a.shape[2])
#print ("Total number of element: \t", tf.size(tensor_a).numpy())

#tensor_b = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)
#tensor_a

Tensor Information
Shape: (6, 300)
Dimension: 2
Size: tf.Tensor(1800, shape=(), dtype=int32)
Rank:  2
DataType of elements:  <dtype: 'float32'>


In [71]:
tensor_b = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)

print ("Tensor Information")
print ("Shape:", tensor_b.shape)
print ("Dimension:", tensor_b.ndim)
print ("Size:",tf.size(tensor_b))
print ("Rank: ",tf.rank(tensor_b).numpy())
print ("DataType of elements: ",tensor_b.dtype)
#print ("Element along axis 0: ",tensor_b.shape[0])
#print ("Element along axis 1: ", tensor_b.shape[1])
#print ("Element along axis 2: ", tensor_b.shape[2])
#print ("Total number of element: \t", tf.size(tensor_b).numpy())

#tensor_b = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)
#tensor_a

Tensor Information
Shape: (6, 300)
Dimension: 2
Size: tf.Tensor(1800, shape=(), dtype=int32)
Rank:  2
DataType of elements:  <dtype: 'float32'>


**Matrix Multiplication**
We will use tf.matmul() method

**Rules:**
1. Inner dimensions must match
(m,n)@(n,p)
for e.g.
(5,7)@(8,9) it will not work because n is different
(5,8)@(8,9) it will work because inner dimension is the same


2. The result matrix has the shape of outer dimension meaning A(m,n) x B(n,p) = (m,p) (4,7)x(7,5)=(4,5)