**Matrix Multiplication**
We will use tf.matmul() method

**Rules:**
1. Inner dimensions must match
(m,n)@(n,p)
for e.g.
(5,7)@(8,9) it will not work because n is different
(5,8)@(8,9) it will work because inner dimension is the same


2. The result matrix has the shape of outer dimension meaning A(m,n) x B(n,p) = (m,p) (4,7)x(7,5)=(4,5)

In [1]:
import tensorflow as tf
import numpy as np

In [4]:
tensor_A=tf.constant([[1,2],[3,4]],dtype=tf.int32)
tensor_B=tf.constant([[1,2],[3,4]],dtype=tf.int32)
print("Shape of A: ",tensor_A.shape)
print("Shape of B: ",tensor_B.shape)

Shape of A:  (2, 2)
Shape of B:  (2, 2)


In [5]:
tensor_C=tf.matmul(tensor_A,tensor_B)
print("Shape of C: ",tensor_C.shape)

Shape of C:  (2, 2)


Transpose: Transpose swaps axes. For 2D matrix shape (m,n) become (n,m) after transpose

In [7]:
tensor_one=tf.constant([
    [[1,2],[2,3]],
    [[4,5],[6,7]]
], dtype=tf.int32)
print(tensor_one)
print("Shape of tensor_one: \t",tensor_one.shape)

tf.Tensor(
[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]], shape=(2, 2, 2), dtype=int32)
Shape of tensor_one: 	 (2, 2, 2)


In [8]:
tensor_one_transpose=tf.transpose(tensor_one)
print (tensor_one_transpose)
print ("Shape of tensor one transpose", tensor_one_transpose.shape)

tf.Tensor(
[[[1 4]
  [2 6]]

 [[2 5]
  [3 7]]], shape=(2, 2, 2), dtype=int32)
Shape of tensor one transpose (2, 2, 2)
